"""Initial migration after reset

Revision ID: 0871fd680202
Revises: 
Create Date: 2025-05-28 19:20:48.499694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0871fd680202'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_responsavel', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('mora_plano_piloto', sa.Boolean(), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('serie', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('plano_adquirido', sa.String(length=50), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('banco', sa.String(length=50), nullable=True),
    sa.Column('agencia', sa.String(length=10), nullable=True),
    sa.Column('conta', sa.String(length=15), nullable=True),
    sa.Column('pix', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('disciplina', sa.String(length=50), nullable=False),
    sa.Column('disponibilidade', sa.String(length=200), nullable=True),
    sa.Column('valor_hora', sa.Float(), nullable=True),
    sa.Column('tipo_atendimento', sa.String(length=50), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=50), nullable=False),
    sa.Column('tipo_aula', sa.String(length=20), nullable=False),
    sa.Column('realizada', sa.Boolean(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('frequencia', sa.Integer(), nullable=True),
    sa.Column('dias_semana', sa.String(length=50), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('aula_principal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['aula_principal_id'], ['aula.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=200), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('tipo_plano', sa.String(length=50), nullable=False),
    sa.Column('assinatura', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=512), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('upload_por', sa.Integer(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['upload_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    op.drop_table('documento')
    op.drop_table('users')
    op.drop_table('contrato')
    op.drop_table('aula')
    op.drop_table('professor')
    op.drop_table('aluno')
    # ### end Alembic commands ###
