"""Adiciona Responsavel e ajusta Contrato para multiplos alunos

Revision ID: 73cb44088256
Revises: b8c486550fac
Create Date: 2025-06-16 15:17:12.789746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cb44088256'
down_revision = 'b8c486550fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contrato_aluno_associacao',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('contrato_id', 'aluno_id')
    )

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_id', sa.Integer(), nullable=True))
        batch_op.drop_column('nome_responsavel')
        batch_op.create_foreign_key('fk_aluno_responsavel_id', 'responsavel', ['responsavel_id'], ['id'])

    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materia_id', sa.Integer(), nullable=True))
        batch_op.alter_column('realizada', existing_type=sa.BOOLEAN(), nullable=False, existing_nullable=True)
        batch_op.create_foreign_key('fk_aula_materia_id', 'materia', ['materia_id'], ['id'])

    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('data_inicio', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('valor_total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('servicos_incluidos', sa.Text(), nullable=True))
        batch_op.drop_constraint('contrato_aluno_id_fkey', type_='foreignkey') # Remova a chave estrangeira antiga
        batch_op.drop_column('aluno_id')
        batch_op.create_foreign_key('fk_contrato_responsavel_id', 'responsavel', ['responsavel_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_responsavel_id', 'responsavel', ['responsavel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_responsavel_id', type_='foreignkey')
        batch_op.drop_column('responsavel_id')

    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contrato_responsavel_id', type_='foreignkey')
        batch_op.add_column(sa.Column('aluno_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('servicos_incluidos')
        batch_op.drop_column('valor_total')
        batch_op.drop_column('data_inicio')
        batch_op.drop_column('responsavel_id')
        batch_op.create_foreign_key('contrato_aluno_id_fkey', 'aluno', ['aluno_id'], ['id'])

    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.drop_constraint('fk_aula_materia_id', type_='foreignkey')
        batch_op.alter_column('realizada', existing_type=sa.BOOLEAN(), nullable=True, existing_nullable=False)
        batch_op.drop_column('materia_id')

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint('fk_aluno_responsavel_id', type_='foreignkey')
        batch_op.add_column(sa.Column('nome_responsavel', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('responsavel_id')

    op.drop_table('contrato_aluno_associacao')
    op.drop_table('responsavel')
    # ### end Alembic commands ###
