"""Adiciona materia_id a aula

Revision ID: b8c486550fac
Revises: eee6cf9759d3
Create Date: 2025-06-05 20:52:57.716520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c486550fac'
down_revision = 'eee6cf9759d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('professor_materia',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('data_associacao', sa.DateTime(), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'materia_id')
    )
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materia_id', sa.Integer(), nullable=True))
        batch_op.alter_column('realizada',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_foreign_key(None, 'materia', ['materia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('realizada',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('materia_id')

    op.drop_table('professor_materia')
    op.drop_table('materia')
    # ### end Alembic commands ###
