"""Corrige referencia user_id em Professor para users.id

Revision ID: ca9a6d5df2f5
Revises: 73cb44088256
Create Date: 2025-06-17 12:01:11.849120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9a6d5df2f5'
down_revision = '73cb44088256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Operações na tabela 'aluno'
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('nome_responsavel')
        batch_op.create_foreign_key(batch_op.f('fk_aluno_responsavel_id_responsavel'), 'responsavel', ['responsavel_id'], ['id'])

    # Operações na tabela 'aula'
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materia_id', sa.Integer(), nullable=True))
        batch_op.alter_column('realizada',
                   existing_type=sa.BOOLEAN(),
                   nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_aula_materia_id_materia'), 'materia', ['materia_id'], ['id'])

    # Operações na tabela 'contrato'
    # Passo 1: Adiciona colunas como nullable=True primeiro
    with op.batch_alter_table("contrato", schema=None) as batch_op:
        batch_op.add_column(sa.Column("responsavel_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("data_inicio", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("valor_total", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("servicos_incluidos", sa.Text(), nullable=True))

    # Passo 2: Preenche as novas colunas com valores padrão para as linhas existentes
    # ATENÇÃO: Substitua os valores padrão (1, '2023-01-01', 0.0, 'Serviços Padrão') por valores que façam sentido para o seu negócio.
    # Se você não tiver um responsavel_id padrão, pode precisar criar um registro de responsável antes de rodar a migração.
    op.execute("UPDATE contrato SET responsavel_id = 1 WHERE responsavel_id IS NULL") # Exemplo: ID 1 de um responsável padrão
    op.execute("UPDATE contrato SET data_inicio = '2023-01-01' WHERE data_inicio IS NULL") # Exemplo: data padrão
    op.execute("UPDATE contrato SET valor_total = 0.0 WHERE valor_total IS NULL") # Exemplo: valor padrão
    op.execute("UPDATE contrato SET servicos_incluidos = 'Serviços Padrão' WHERE servicos_incluidos IS NULL") # Exemplo: texto padrão

    # Passo 3: Altera as colunas para nullable=False (se necessário) e adiciona/remove FKs
    with op.batch_alter_table("contrato", schema=None) as batch_op:
        batch_op.alter_column("responsavel_id", existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column("data_inicio", existing_type=sa.Date(), nullable=False)
        batch_op.alter_column("valor_total", existing_type=sa.Float(), nullable=False)

        # Restante das operações na tabela contrato
        batch_op.create_foreign_key(batch_op.f("fk_contrato_responsavel_id_responsavel"), "responsavel", ["responsavel_id"], ["id"])
        batch_op.drop_column("aluno_id")

    # Operações na tabela 'professor'
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_professor_user_id'), ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_professor_user_id_users'), 'users', ['user_id'], ['id'])

    # Operações na tabela 'users'
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_responsavel_id_responsavel'), 'responsavel', ['responsavel_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Operações na tabela 'users'
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_responsavel_id_responsavel'), type_='foreignkey')
        batch_op.drop_column('responsavel_id')

    # Operações na tabela 'professor'
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_professor_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_professor_user_id'), type_='unique')
        batch_op.drop_column('user_id')

    # Operações na tabela 'contrato' (reverter as mudanças)
    with op.batch_alter_table("contrato", schema=None) as batch_op:
        # Adiciona de volta a coluna aluno_id
        batch_op.add_column(sa.Column('aluno_id', sa.INTEGER(), nullable=False))
        # Remove a chave estrangeira para responsavel
        batch_op.drop_constraint(batch_op.f("fk_contrato_responsavel_id_responsavel"), type_='foreignkey')
        # Remove as novas colunas
        batch_op.drop_column('servicos_incluidos')
        batch_op.drop_column('valor_total')
        batch_op.drop_column('data_inicio')
        batch_op.drop_column('responsavel_id')

    # Operações na tabela 'aula'
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_aula_materia_id_materia'), type_='foreignkey')
        batch_op.alter_column('realizada',
                   existing_type=sa.BOOLEAN(),
                   nullable=True)
        batch_op.drop_column('materia_id')

    # Operações na tabela 'aluno'
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_responsavel', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_aluno_responsavel_id_responsavel'), type_='foreignkey')

    # ### end Alembic commands ###