"""Adiciona campos financeiros na tabela Aula

Revision ID: eee6cf9759d3
Revises: 0871fd680202
Create Date: 2025-06-05 16:48:06.556206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee6cf9759d3'
down_revision = '0871fd680202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_aula', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('custo_aula', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('deslocamento', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.drop_column('observacoes')
        batch_op.drop_column('deslocamento')
        batch_op.drop_column('custo_aula')
        batch_op.drop_column('valor_aula')

    # ### end Alembic commands ###
